### ISSUE TITLE
DOCS: M() links in module docstrings should use FQCN

### ISSUE THREAD

**Issue by acozine** [ansible-collections/community.azure#4]
##### SUMMARY
Update all M() links to use FQCN. See https://github.com/ansible-community/antsibull/pull/92 for more detail on how links work.

List of modules with M() links:

- azure_rm_dnsrecordset_info.py
- azure_rm_manageddisk_info.py
- azure_rm_manageddisk.py
- azure_rm_networkinterface_info.py
- azure_rm_virtualmachineextension.py
- azure_rm_virtualmachinescaleset_info.py (2 instances)
- azure_rm_virtualmachinescaleset.py
- azure_rm_virtualnetwork_info.py
- 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
multiple modules

##### ANSIBLE VERSION
2.10

**Comment by bmillemathias** [comment]
https://github.com/ansible-collections/overview/issues/89

**Comment by Andersson007** [comment]
@acozine i think this could be closed via https://github.com/ansible-collections/community.azure/pull/5

**Comment by acozine** [comment]
@Andersson007 thank you for the PR! Closed by #5.
